### PR TITLE
Fixed all the files that didn't compile on FreeBSD

### PR DESCRIPTION
**Pull request by alex4o**
I fixed the compile problems. The test are still running on CheriBSD but I hope that they will pass.

### CODE REVIEW

**Comment by alex4o** [comment]
There is no bors config for this repo, But I can add one?

**Comment by ltratt** [comment]
It has a `.buildbot.sh` so I assumed it would have bors too! Yes, it would be good to add bors here, as I suspect we might make subsequent changes.

**Comment by alex4o** [comment]
Done

**Comment by alex4o** [comment]
bors try

**Comment by alex4o** [comment]
bors try-

**Comment by alex4o** [comment]
Can we try merging this again?

**Pull request merged**
