### PR TITLE
Remove files that produce errors.

### PR DESCRIPTION
**Pull request by alex4o**

### CODE REVIEW

**Comment by ltratt** [comment]
I notice the PR says "remove files" plural but only one file has been `rm`d in the PR. Is that intentional?

**Comment by alex4o** [comment]
No it's not. but that means that I have deleted a file not tracked by git. 
I can rename that if it is a problem.

**Comment by ltratt** [comment]
Basically my question is: is this PR complete as-is or does it need to be fixed? I don't know the details, so I'm relying on you to tell me "yes it's complete as-is" or "no, I need to fix something" :)

**Comment by alex4o** [comment]
yes the PR is fine, I can change the name.

**Comment by ltratt** [comment]
Please do so and force push an updated commit message.

**Comment by alex4o** [comment]
Done and I have added a second commit that removes a few lines.

**Comment by ltratt** [comment]
OK, although don't force push and add new commits next time please :)

bors r+

**Pull request merged**
